# Generated by Django 4.2.7 on 2023-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
