# Generated by Django 4.2.7 on 2023-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_client_alter_contract_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
