# Generated by Django 4.2.7 on 2023-11-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_date_created_alter_client_last_update'),
        ('contracts', '0007_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
